<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Wobkey.Crush80.Emulator/Wobkey.Crush80.Emulator.csproj" />
    <ProjectReference Include="../../../sdk/dotnet/adapters/Wobkey.Crush80.Adapter/Wobkey.Crush80.Adapter.csproj" />
  </ItemGroup>
</Project>
