namespace Wobkey.Crush80.Emulator;

/// <summary>Hosts one emulated keyboard for a remote SDK process and a loopback browser visualizer.</summary>
public sealed class Crush80EmulatorServer : IAsyncDisposable
{
    private readonly Crush80EmulatedTransport _transport;
    private readonly Crush80Visualizer _visualizer;
    private readonly Crush80IpcServer _ipcServer;
    private int _disposed;

    private Crush80EmulatorServer(
        Crush80EmulatedTransport transport,
        Crush80Visualizer visualizer,
        Crush80IpcServer ipcServer)
    {
        _transport = transport;
        _visualizer = visualizer;
        _ipcServer = ipcServer;
    }

    /// <summary>Gets the local browser visualizer address.</summary>
    public Uri VisualizerUri => _visualizer.Uri;

    /// <summary>Gets the loopback endpoint accepted by <see cref="Crush80RemoteTransport"/>.</summary>
    public Uri TransportEndpoint => _ipcServer.Endpoint;

    /// <summary>Captures the current emulated keyboard state.</summary>
    public Crush80EmulatorState CaptureState() => _transport.CaptureState();

    /// <summary>Starts an idle standalone emulator. No RGB frames are generated by the server.</summary>
    public static async ValueTask<Crush80EmulatorServer> StartAsync(
        int visualizerPort = 5080,
        int transportPort = 5081,
        CancellationToken cancellationToken = default)
    {
        var transport = new Crush80EmulatedTransport(clientConnected: false);
        Crush80Visualizer? visualizer = null;
        Crush80IpcServer? ipcServer = null;
        try
        {
            visualizer = await Crush80Visualizer.StartAsync(transport, visualizerPort, cancellationToken)
                .ConfigureAwait(false);
            ipcServer = Crush80IpcServer.Start(transport, transportPort);
            return new Crush80EmulatorServer(transport, visualizer, ipcServer);
        }
        catch
        {
            if (ipcServer is not null)
                await ipcServer.DisposeAsync().ConfigureAwait(false);
            if (visualizer is not null)
                await visualizer.DisposeAsync().ConfigureAwait(false);
            await transport.DisposeAsync().ConfigureAwait(false);
            throw;
        }
    }

    /// <summary>Stops accepting clients, closes the visualizer, and disposes the emulated device.</summary>
    public async ValueTask DisposeAsync()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
            return;

        await _ipcServer.DisposeAsync().ConfigureAwait(false);
        await _visualizer.DisposeAsync().ConfigureAwait(false);
        await _transport.DisposeAsync().ConfigureAwait(false);
    }
}
